---
title: "DSP 539: Climate, Federal, and Energy Spending Analysis in R"
author: "Emiton Alves"
date: "4/30/2019"
output: pdf_document
---

```{r setup, include=FALSE}
# Run install lines once within a project
#install.packages("tidyverse")
#install.packages("reshape2")

# Libraries
library("tidyverse")
library("reshape2")

# Import data
climate_spend <- read.csv("data/climate_spending.csv")
energy_spend <- read.csv("data/energy_spending.csv")
fed_spend <- read.csv("data/fed_r_d_spending.csv")
```

*Note: All R squared values and p-values exist in inline code. For a given Figure, just find its named code chunk and run the code under 'linear analysis'.*  

# General Overview
Here is my report.


```{r overview_climate, echo=FALSE, warning=FALSE}
# Climate budget yearly growth by department + linear model
ggplot(data = climate_spend, mapping = aes(x = year, y = gcc_spending, color = department)) +
  geom_line() +
  scale_y_log10() +
  ggtitle("Figure 1 - US Climate Spending per department") +
  xlab("Year") + 
  ylab("Dollars Spent (USD)")
```

```{r overview_energy, echo=FALSE, warning=FALSE}
# Energy budget yearly growth by department
ggplot(data = energy_spend, mapping = aes(x = year, y = energy_spending, color = department)) +
  geom_line() +
  scale_y_log10() +
  ggtitle("Figure 2 - US Energy Spending per department") +
  xlab("Year") + 
  ylab("Dollars Spent (USD)")
```

```{r overview_federal, echo=FALSE, warning=FALSE}
# Federal budget yearly growth by department
ggplot(data = fed_spend, mapping = aes(x = year, y = rd_budget, color = department)) +
  geom_line() +
  scale_y_log10() +
  ggtitle("Figure 3 - US Federal Spending per department") +
  xlab("Year") + 
  ylab("Dollars Spent (USD)")
```

```{r gdp_growth, echo=FALSE, warning=FALSE}
# GDP Growth yearly growth rate
# Get  yearly GDP by selecting only one department
yearly_gdp <- fed_spend %>%
  filter(department == "DOD") %>%
  select(year, gdp)

# total_fed_spend
yearly_outlays <- fed_spend %>%
  filter(department == "DOD") %>%
  select(year, total_outlays)

# discretionary_fed_spend
yearly_disc_spend <- fed_spend %>%
  filter(department == "DOD") %>%
  select(year, discretionary_outlays)

# GDP, spending discretionary spending
all_spending <- data.frame("year" = yearly_gdp$year,
                           "gdp" = yearly_gdp$gdp,
                           "total_spending" = yearly_outlays$total_outlays,
                           "disc_spending" = yearly_disc_spend$discretionary_outlays)

spending_melt <- melt(all_spending, id=c("year"))

ggplot(spending_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red","green", "blue"),
                     labels = c("GDP", "Total Spending", "Discretionary Spending")) + 
  ggtitle("Figure 4 - GDP versus Spending") +
  xlab("Year") +
  ylab("Dollars (USD)")
```

```{r spending, echo=FALSE, warning=FALSE}
# Rate of change for yearly gdp, total spending, and discretionary spending
gdp_change <- 100*diff(yearly_gdp$gdp)/yearly_gdp[-nrow(yearly_gdp),]$gdp
total_outlay_change <- 100*diff(yearly_outlays$total_outlays)/yearly_outlays[-nrow(yearly_outlays),]$total_outlays
disc_outlay_change <- 100*diff(yearly_disc_spend$discretionary_outlays)/yearly_disc_spend[-nrow(yearly_disc_spend),]$discretionary_outlays

gdp_budget_roc <- data.frame("year" = yearly_gdp$year[2:42], 
                             "gdp_change" = gdp_change,
                             "outlay_change" = total_outlay_change,
                             "disc_change" = disc_outlay_change)

# Plot results
roc_melt <- melt(gdp_budget_roc, id=c("year"))

ggplot(roc_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red","green", "blue"),
                     labels = c("GDP", "Total Spending", "Discretionary Spending")) +
  ggtitle("Figure 5 - Rate of Change: GDP, Total Spendng, Discretionary Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_spending_model <- lm(value ~ year, data = roc_melt)
# R-squared
gdp_spending_r2 <- summary(gdp_spending_model)$r.squared
# p-value
gdp_spending_pv <- summary(gdp_spending_model)$coefficients[2,4]
```

```{r gdp_department_roc, echo=FALSE, warning=FALSE}
fed_mean_spend <- fed_spend %>%
  group_by(year) %>%
  summarize(average_spend = mean(rd_budget))

energy_mean_spend <- energy_spend %>%
  group_by(year) %>%
  summarize(average_spend = mean(energy_spending))

climate_mean_spend <- climate_spend %>%
  group_by(year) %>%
  summarize(average_spend = mean(gcc_spending))


fed_mean_change <- 100*diff(fed_mean_spend$average_spend)/fed_mean_spend[-nrow(fed_mean_spend),]$average_spend
energy_mean_change <- 100*diff(energy_mean_spend$average_spend)/energy_mean_spend[-nrow(energy_mean_spend),]$average_spend
climate_mean_change <- 100*diff(climate_mean_spend$average_spend)/climate_mean_spend[-nrow(climate_mean_spend),]$average_spend


fed_roc <- data.frame("year" = fed_mean_spend$year[2:42],
                      "fed_change" = fed_mean_change,
                      "gdp_change" = gdp_change)

energy_roc <- data.frame("year" = energy_mean_spend$year[2:22],
                         "energy_change" = energy_mean_change,
                         "gdp_change" = gdp_change[22:42])

energy_roc <- energy_roc[-nrow(energy_roc),] # Remove last row b/c there is no GDP data for 2018

climate_roc <- data.frame("year" = climate_mean_spend$year[2:18],
                          "climate_change" = climate_mean_change,
                          "gdp_change" = gdp_change[25:41])
```

```{r fed_department_roc, echo=FALSE, warning=FALSE}
fed_melt <- melt(fed_roc, id=c("year"))
ggplot(fed_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 6 - Rate of Change: GDP versus Federal Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_fed_model <- lm(value ~ year, data = fed_melt)
# R-squared
gdp_fed_r2 <- summary(gdp_fed_model)$r.squared
# p-value
gdp_fed_pv <- summary(gdp_fed_model)$coefficients[2,4]
```

```{r energy_department_roc, echo=FALSE, warning=FALSE}
energy_melt <- melt(energy_roc, id=c("year"))
ggplot(energy_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 7 - Rate of Change: GDP versus Energy Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_energy_model <- lm(value ~ year, data = energy_melt)
# R-squared
gdp_energy_r2 <- summary(gdp_energy_model)$r.squared
# p-value
gdp_energy_pv <- summary(gdp_energy_model)$coefficients[2,4]
```

```{r climate_department_roc, echo=FALSE, warning=FALSE,message=FALSE}
climate_melt <- melt(climate_roc, id=c("year"))
ggplot(climate_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 8 - Rate of Change: GDP versus Climate Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_climate_model <- lm(value ~ year, data = climate_melt)
# R-squared
gdp_climate_r2 <- summary(gdp_climate_model)$r.squared
# p-value
gdp_climate_pv <- summary(gdp_climate_model)$coefficients[2,4]
```

```{r gdp_per_department_setup, echo=FALSE, warning=FALSE}
" 
function: department_matrix_roc
description: Given a data frame and a column, gets the 
             rate of change per department in said column
returns: matrix where each col is department, and each row
         is percent change from previous year
"
department_matrix_roc <- function(df, monies_col) {
  departments <- unique(df$department)
  dep_one_yearly <- filter(df, department == as.character(departments[1])) # all unique years
  df_years <- nrow(dep_one_yearly) # range of years in DF
  matrix_roc <- data.frame("year" = dep_one_yearly$year[2:df_years])
  
  for (dep in departments) {
    # Get yearly spending for department
    curr_dep <- df %>%
      filter(department == as.character(dep)) %>%
      select(year, monies_col)
    
    curr_dep_roc <- 100*diff(curr_dep[[monies_col]])/curr_dep[-nrow(curr_dep),][[monies_col]]
    matrix_roc[dep] <- curr_dep_roc
  }
  matrix_roc
}

fed_department_roc <- department_matrix_roc(fed_spend, "rd_budget")
fed_department_roc$gdp_change <- gdp_budget_roc$gdp_change

energy_department_roc <- department_matrix_roc(energy_spend, "energy_spending")
energy_department_roc <- energy_department_roc[-nrow(energy_department_roc),] # remove last row, no GDP for 2018
energy_department_roc$gdp_change <- gdp_budget_roc$gdp_change[22:41]

climate_department_roc <- department_matrix_roc(climate_spend, "gcc_spending")
climate_department_roc$gdp_change <- gdp_budget_roc$gdp_change[25:41]
```

```{r federal_per_department, echo=FALSE, warning=FALSE}
# Fix NaN values
is.nan.data.frame <- function(x)
do.call(cbind, lapply(x, is.nan))
fed_department_roc[is.nan(fed_department_roc)] <- 0

# Get rid of Inf value
fed_department_roc$DHS[26] = 0

fed_roc_melt <- melt(fed_department_roc, id=c("year"))
ggplot(fed_roc_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 9 - Rate of Change: GDP and Federal Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_fed_department_model <- lm(value ~ year, data = fed_roc_melt)
# R-squared
gdp_fed_r2 <- summary(gdp_fed_department_model)$r.squared
# p-value
gdp_fed_pv <- summary(gdp_fed_department_model)$coefficients[2,4]
```

```{r energy_per_department, echo=FALSE, warning=FALSE}
energy_roc_melt <- melt(energy_department_roc, id=c("year"))
ggplot(energy_roc_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 10 - Rate of Change: GDP and Energy Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_energy_department_model <- lm(value ~ year, data = energy_roc_melt)
# R-squared
gdp_energy_r2 <- summary(gdp_energy_department_model)$r.squared
# p-value
gdp_energy_pv <- summary(gdp_energy_department_model)$coefficients[2,4]
```

```{r climate_per_department, echo=FALSE, warning=FALSE}
climate_roc_melt <- melt(climate_department_roc, id=c("year"))
ggplot(climate_roc_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 11 - Rate of Change: GDP and Climate Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
gdp_climate_department_model <- lm(value ~ year, data = climate_roc_melt)
# R-squared
gdp_climate_r2 <- summary(gdp_climate_department_model)$r.squared
# p-value
gdp_climate_pv <- summary(gdp_climate_department_model)$coefficients[2,4]
```

```{r total_spend_roc_setup, echo=FALSE, warning=FALSE}
fed_roc_total_spend <- data.frame("year" = fed_mean_spend$year[2:42],
                      "fed_change" = fed_mean_change,
                      "total_spending_change" = total_outlay_change)

energy_roc_total_spend <- data.frame("year" = energy_mean_spend$year[2:22],
                         "energy_change" = energy_mean_change,
                         "total_spending_change" = total_outlay_change[22:42])
energy_roc_total_spend <- energy_roc_total_spend[-nrow(energy_roc_total_spend),] # Remove last row b/c there is no GDP data for 2018

climate_roc_total_spend <- data.frame("year" = climate_mean_spend$year[2:18],
                          "climate_change" = climate_mean_change,
                          "total_spending_change" = total_outlay_change[25:41])
```

```{r total_spend_vs_fed, echo=FALSE, warning=FALSE}
fed_melt_total_spend <- melt(fed_roc_total_spend, id=c("year"))
ggplot(fed_melt_total_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 12 - Rate of Change: Total Spending versus Federal Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_fed_model <- lm(value ~ year, data = fed_melt_total_spend)
# R-squared
total_spend_fed_r2 <- summary(total_spend_fed_model)$r.squared
# p-value
total_spend_fed_pv <- summary(total_spend_fed_model)$coefficients[2,4]
```

```{r total_spend_vs_energy, echo=FALSE, warning=FALSE}
energy_melt_total_spend <- melt(energy_roc_total_spend, id=c("year"))
ggplot(energy_melt_total_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 13 - Rate of Change: Total Spending versus Energy Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_energy_model <- lm(value ~ year, data = energy_melt_total_spend)
# R-squared
total_spend_energy_r2 <- summary(total_spend_energy_model)$r.squared
# p-value
total_spend_energy_pv <- summary(total_spend_energy_model)$coefficients[2,4]
```

```{r total_spend_vs_climate, echo=FALSE, warning=FALSE}
climate_melt_total_spend <- melt(climate_roc_total_spend, id=c("year"))
ggplot(climate_melt_total_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 14 - Rate of Change: Total Spending versus Climate Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_climate_model <- lm(value ~ year, data = climate_melt_total_spend)
# R-squared
total_spend_climate_r2 <- summary(total_spend_climate_model)$r.squared
# p-value
total_spend_climate_pv <- summary(total_spend_climate_model)$coefficients[2,4]
```

```{r total_spend_roc_versus_department, echo=FALSE, warning=FALSE}
fed_department_roc_total_spend <- fed_department_roc[,!(names(fed_department_roc) %in% c("gdp_change"))]
fed_department_roc_total_spend$spending_change <- gdp_budget_roc$outlay_change

energy_department_roc_total_spend <- energy_department_roc[,!(names(energy_department_roc) %in% c("gdp_change"))]
energy_department_roc_total_spend$spending_change <- gdp_budget_roc$outlay_change[22:41]

climate_department_roc_total_spend <- climate_department_roc[,!(names(climate_department_roc) %in% c("gdp_change"))]
climate_department_roc_total_spend$spending_change <- gdp_budget_roc$outlay_change[25:41]
```

```{r total_spend_vs_fed_department, echo=FALSE, warning=FALSE}
fed_roc_total_spend_melt <- melt(fed_department_roc_total_spend, id=c("year"))
ggplot(fed_roc_total_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 15 - Rate of Change: Total and Federal Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_fed_department_model <- lm(value ~ year, data = fed_roc_total_spend_melt)
# R-squared
total_spend_fed_r2 <- summary(total_spend_fed_department_model)$r.squared
# p-value
total_spend_fed_pv <- summary(total_spend_fed_department_model)$coefficients[2,4]
```

```{r total_spend_vs_energy_department, echo=FALSE, warning=FALSE}
energy_roc_total_spend_melt <- melt(energy_department_roc_total_spend, id=c("year"))
ggplot(energy_roc_total_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 16 - Rate of Change: Total and Energy Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_energy_department_model <- lm(value ~ year, data = energy_roc_total_spend_melt)
# R-squared
total_spend_energy_r2 <- summary(total_spend_energy_department_model)$r.squared
# p-value
total_spend_energy_pv <- summary(total_spend_energy_department_model)$coefficients[2,4]
```

```{r total_spend_vs_climate_department, echo=FALSE, warning=FALSE}
climate_roc_total_spend_melt <- melt(climate_department_roc_total_spend, id=c("year"))
ggplot(climate_roc_total_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 17 - Rate of Change: Total and Climate Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
total_spend_climate_department_model <- lm(value ~ year, data = climate_roc_total_spend_melt)
# R-squared
total_spend_climate_r2 <- summary(total_spend_climate_department_model)$r.squared
# p-value
total_spend_climate_pv <- summary(total_spend_climate_department_model)$coefficients[2,4]
```

```{r disc_spend_roc_setup, echo=FALSE, warning=FALSE}
fed_roc_disc_spend <- data.frame("year" = fed_mean_spend$year[2:42],
                                  "fed_change" = fed_mean_change,
                                  "disc_spending_change" = disc_outlay_change)

energy_roc_disc_spend <- data.frame("year" = energy_mean_spend$year[2:22],
                                     "energy_change" = energy_mean_change,
                                     "disc_spending_change" = disc_outlay_change[22:42])
energy_roc_disc_spend <- energy_roc_disc_spend[-nrow(energy_roc_disc_spend),] # Remove last row b/c there is no GDP data for 2018

climate_roc_disc_spend <- data.frame("year" = climate_mean_spend$year[2:18],
                                      "climate_change" = climate_mean_change,
                                      "disc_spending_change" = disc_outlay_change[25:41])
```

```{r disc_spend_vs_fed, echo=FALSE, warning=FALSE}
fed_melt_disc_spend <- melt(fed_roc_disc_spend, id=c("year"))
ggplot(fed_melt_disc_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 18 - Rate of Change: Discretionary Spending versus Federal Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_fed_model <- lm(value ~ year, data = fed_melt_disc_spend)
# R-squared
disc_spend_fed_r2 <- summary(disc_spend_fed_model)$r.squared
# p-value
disc_spend_fed_pv <- summary(disc_spend_fed_model)$coefficients[2,4]
```

```{r disc_spend_vs_energy, echo=FALSE, warning=FALSE}
energy_melt_disc_spend <- melt(energy_roc_disc_spend, id=c("year"))
ggplot(energy_melt_disc_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 19 - Rate of Change: Discretionary Spending versus Energy Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_energy_model <- lm(value ~ year, data = energy_melt_disc_spend)
# R-squared
disc_spend_energy_r2 <- summary(disc_spend_energy_model)$r.squared
# p-value
disc_spend_energy_pv <- summary(disc_spend_energy_model)$coefficients[2,4]
```

```{r disc_spend_vs_climate, echo=FALSE, warning=FALSE}
climate_melt_disc_spend <- melt(climate_roc_disc_spend, id=c("year"))
ggplot(climate_melt_disc_spend) +
  geom_line(aes(x = year, y = value, color=variable)) +
  scale_color_manual(values = c("red", "blue")) +
  ggtitle("Figure 20 - Rate of Change: Discretionary Spending versus Climate Spending") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_climate_model <- lm(value ~ year, data = climate_melt_disc_spend)
# R-squared
disc_spend_climate_r2 <- summary(disc_spend_climate_model)$r.squared
# p-value
disc_spend_climate_pv <- summary(disc_spend_climate_model)$coefficients[2,4]
```

```{r disc_spend_roc_versus_department, echo=FALSE, warning=FALSE}
fed_department_roc_disc_spend <- fed_department_roc[,!(names(fed_department_roc) %in% c("gdp_change"))]
fed_department_roc_disc_spend$spending_change <- gdp_budget_roc$disc_change

energy_department_roc_disc_spend <- energy_department_roc[,!(names(energy_department_roc) %in% c("gdp_change"))]
energy_department_roc_disc_spend$spending_change <- gdp_budget_roc$disc_change[22:41]

climate_department_roc_disc_spend <- climate_department_roc[,!(names(climate_department_roc) %in% c("gdp_change"))]
climate_department_roc_disc_spend$spending_change <- gdp_budget_roc$disc_change[25:41]
```

```{r disc_spend_vs_fed_department, echo=FALSE, warning=FALSE}
fed_roc_disc_spend_melt <- melt(fed_department_roc_disc_spend, id=c("year"))
ggplot(fed_roc_disc_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 21 - Rate of Change: Discretionary and Federal Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_fed_department_model <- lm(value ~ year, data = fed_roc_disc_spend_melt)
# R-squared
disc_spend_fed_r2 <- summary(disc_spend_fed_department_model)$r.squared
# p-value
disc_spend_fed_pv <- summary(disc_spend_fed_department_model)$coefficients[2,4]
```

```{r disc_spend_vs_energy_department, echo=FALSE, warning=FALSE}
energy_roc_disc_spend_melt <- melt(energy_department_roc_disc_spend, id=c("year"))
ggplot(energy_roc_disc_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 22 - Rate of Change: Discretionary and Energy Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_energy_department_model <- lm(value ~ year, data = energy_roc_disc_spend_melt)
# R-squared
disc_spend_energy_r2 <- summary(disc_spend_energy_department_model)$r.squared
# p-value
disc_spend_energy_pv <- summary(disc_spend_energy_department_model)$coefficients[2,4]
```

```{r disc_spend_vs_climate_department, echo=FALSE, warning=FALSE}
climate_roc_disc_spend_melt <- melt(climate_department_roc_disc_spend, id=c("year"))
ggplot(climate_roc_disc_spend_melt) +
  geom_line(aes(x = year, y = value, color=variable)) +
  ggtitle("Figure 23 - Rate of Change: Discretionary and Climate Spending per Department") +
  xlab("Year") +
  ylab("Percent Change (%)")

# Linear analysis
disc_spend_climate_department_model <- lm(value ~ year, data = climate_roc_disc_spend_melt)
# R-squared
disc_spend_climate_r2 <- summary(disc_spend_climate_department_model)$r.squared
# p-value
disc_spend_climate_pv <- summary(disc_spend_climate_department_model)$coefficients[2,4]
```